[package]
name = "get_json"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.16", features = ["blocking",] }
serde_json = "1.0.95"
serde = { version = "1.0", features = ["derive"] }


[dev-dependencies]
assert_cmd = "2.0.8"
